apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: my-project
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    description: Example Project
    sourceRepos:
        - '*'
        - https://github.com/example/repo4.git
        - https://github.com/example/repo5.git
        - https://github.com/example/repo6.git
    destinations:
        - namespace: guestbook
          server: https://kubernetes.default.svc
          name: in-cluster
    clusterResourceWhitelist:
        - group: ""
          kind: Namespace
    namespaceResourceBlacklist:
        - group: ""
          kind: ResourceQuota
        - group: ""
          kind: LimitRange
        - group: ""
          kind: NetworkPolicy
    namespaceResourceWhitelist:
        - group: apps
          kind: Deployment
        - group: apps
          kind: StatefulSet
    orphanedResources:
        warn: false
    roles:
        - name: read-only
          description: Read-only privileges to my-project
          policies:
            - p, proj:my-project:read-only, applications, get, my-project/*, allow
          groups:
            - my-oidc-group
          jwtTokens: []
        - name: ci-role
          description: Sync privileges for guestbook-dev
          policies:
            - p, proj:my-project:ci-role, applications, sync, my-project/guestbook-dev, allow
          groups: []
          jwtTokens:
            - iat: 1535390316
    syncWindows:
        - kind: allow
          schedule: 10 1 * * *
          duration: 1h
          applications:
            - '*-prod'
          manualSync: true
          namespaces: []
          clusters: []
        - kind: deny
          schedule: 0 22 * * *
          duration: 1h
          applications: []
          manualSync: false
          namespaces:
            - default
          clusters: []
        - kind: allow
          schedule: 0 23 * * *
          duration: 1h
          applications: []
          manualSync: false
          namespaces: []
          clusters:
            - in-cluster
            - cluster1
    permitOnlyProjectScopedClusters: false
    sourceNamespaces:
        - argocd-apps-*
